web/project/users/views.py
# project/users/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, request, redirect, url_for, flash, abort
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime
from twilio.rest import TwilioRestClient

from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm
from project import db, mail, app
from project.models import User


################
#### config ####
################

users_blueprint = Blueprint('users', __name__)


##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)


def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token = password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)


def send_new_user_text_message(new_user_email):
    client = TwilioRestClient(app.config['ACCOUNT_SID'], app.config['AUTH_TOKEN'])
    message = client.messages.create(
        body="Kennedy Family Recipes... new user registered: {}".format(new_user_email),  # Message body, if any
        to=app.config['ADMIN_PHONE_NUMBER'],
        from_=app.config['TWILIO_PHONE_NUMBER']
    )
    # flash('Text message sent to {}: {}'.format(app.config['ADMIN_PHONE_NUMBER'], message.body), 'success')
    return


################
#### routes ####
################

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)
                if 'ACCOUNT_SID' in app.config and not app.config['TESTING']:
                    send_new_user_text_message(new_user.email)
                flash('Thanks for registering!  Please check your email to confirm your email address.', 'success')
                return redirect(url_for('recipes.user_recipes', recipe_type='All'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('recipes.user_recipes', recipe_type='All'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('users.login'))


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Thank you for confirming your email address!', 'success')

    return redirect(url_for('recipes.public_recipes'))


@users_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user.email)
            flash('Please check your email for a password reset link.', 'success')
        else:
            flash('Your email address must be confirmed before attempting a password reset.', 'error')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)


@users_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('The password reset link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)


@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    return render_template('user_profile.html')


@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash('Email changed!  Please confirm your new email address (link sent to new email).', 'success')
                    return redirect(url_for('users.user_profile'))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form)


@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Password has been updated!', 'success')
            return redirect(url_for('users.user_profile'))

    return render_template('password_change.html', form=form)


@users_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        flash('Email sent to confirm your email address.  Please check your email!', 'success')
    except IntegrityError:
        flash('Error!  Unable to send email to confirm your email address.', 'error')

    return redirect(url_for('users.user_profile'))


@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)
    else:

web/project/templates/410.html
{% extends "layout.html" %}

{% block content %}

  <h1>Gone</h1>
  <h4>The target resource is no longer available at the origin server and that this condition is likely to be permanent.</h4>
  <h4><a href="{{ url_for('recipes.public_recipes') }}">Kennedy Family Recipes</a></h4>

{% endblock %}

web/project/templates/_form_macros.html
{% macro render_field(field) %}
  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_field_without_label(field) %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_boolean_field(field) %}
  <dd>{{ field(**kwargs)|safe }} {{ field.label }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_errors(field) %}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
{% endmacro %}

web/project/templates/admin_view_users.html
{% extends "layout.html" %}

{% block content %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Administrative Page: List of Users</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>Role</th>
          <th>Registration Date</th>
          <th>Email Confirmed?</th>
          <th>Email Confirmed On</th>
          <th>Last Login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.role }} </td>
            <td> {{ user.registered_on }} </td>
            <td> {{ user.email_confirmed }} </td>
            <td> {{ user.email_confirmed_on }} </td>
            <td> {{ user.last_logged_in }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

web/project/templates/email_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Email Change</h2>
  </div>

  <p>Current Email: {{ current_user.email }}</p>
  <p>Please enter your new email address:</p>
  <form action="{{ url_for('users.user_email_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field_without_label(form.email, placeholder="Enter New Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

web/project/templates/email_confirmation.html
{# project/templates/email_confirmation.html #}

Your account on Kennedy Family Recipes was successfully created.<br>
Please click the link below to confirm your email address and<br>
activate your account:
 
<p>
<a href="{{ confirm_url }}">{{ confirm_url }}</a>
</p>

<p>
--<br>
Questions? Comments? Email kennedyfamilyrecipes@gmail.com.
</p>

web/project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Kennedy Family Recipe App">
    <meta name="author" content="Patrick Kennedy">
    <title>Kennedy Family Recipe App</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#recipes-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('recipes.public_recipes') }}">Kennedy Family Recipes</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Breakfast') }}">Breakfast</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Lunch') }}">Lunch</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Dinner') }}">Dinner</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Dessert') }}">Dessert</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Side Dish') }}">Side Dish</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Drink') }}">Drink</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='All') }}">All Recipes</a></li>
              </ul>
            </li>
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('recipes.add_recipe') }}">Add Recipe</a></li>
              <li><a href="{{ url_for('recipes.whats_for_dinner') }}">What's for Dinner?</a></li>
              <li><a href="{{ url_for('users.logout') }}">Log Out</a></li>
              {% if current_user.role == "admin" %}
                <li><a href="{{ url_for('users.admin_view_users') }}">View Users (Admin)</a></li>
              {% endif %}
            {% else %}
              <li><a href="{{ url_for('users.register') }}">Register</a></li>
              <li><a href="{{ url_for('users.login') }}">Log In</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('users.user_profile') }}">{{current_user.email}}</a></li>
            {% else %}
              <li><a href="#">Welcome!</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <div class="content">

        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}

        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}

<!--
        {% for debug_message in get_flashed_messages(category_filter=["debug"]) %}
          <div class="alert alert-info alert-dismissible">{{ debug_message }}</div>
        {% endfor %}
-->
        <!-- child template -->
        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>Patrick Kennedy - 2017</p>
      </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

web/project/templates/login.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
  <div class="page-header">
    <h2>Log In</h2>
  </div>
  <form action="{{ url_for('users.login') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Log In</button>
  </form>
  <br>
  <p><em>Need an account? </em><a href="/register">Signup!!</a></p>
  <p><em>Forgot your password? </em><a href="/reset">Reset!!</a></p>
</div>

{% endblock %}

web/project/templates/password_reset_email.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">
  <div class="page-header">
    <h2>Email Address:</h2>
  </div>
  <form action="{{ url_for('users.reset') }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Enter Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Submit</button>
  </form>
</div>

{% endblock %}

web/project/templates/recipe_detail.html
{% extends "layout.html" %}
{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>{{ recipe.recipe_title }}
      {% if recipe.dairy_free_recipe %}
        <span class="label label-info" style="font-size:12px;">Dairy-Free</span>
      {% endif %}
      {% if recipe.soy_free_recipe %}
        <span class="label label-success" style="font-size:12px;">Soy-Free</span>
      {% endif %}
    </h2>
    <h5>
      {% if recipe.user_id == current_user.id %}
        <a href="{{ url_for('recipes.edit_recipe', recipe_id=recipe.id) }}">Edit</a>
        |
        <a href="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}">Delete</a>
      {% endif %}
    </h5>
  </div>


  <div class="row">
    <div class="col-xs-6 col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Recipe Details</div>
        <div class="panel-body"><b>Description:</b> {{ recipe.recipe_description }}</div>
        <div class="panel-body"><b>Public or Private:</b>
          {% if recipe.is_public %}
            Public
          {% else %}
            Private
          {% endif %}
        </div>
        <div class="panel-body"><b>Recipe Type:</b> {{ recipe.recipe_type }}</div>
        <div class="panel-body"><b>Rating (1-worst to 10-best):</b> {{ recipe.rating }}</div>
        <div class="panel-body"><b>Inspiration:</b> {{ recipe.inspiration }}</div>
      </div>
   </div>

    <div class="col-xs-6 col-md-8">
      {% if recipe.image_url %}
        <img class="center-block img-responsive" src="{{ recipe.image_url }}" alt="{{ recipe.image_filename }}" style="width:600px;height:450px;margin-bottom:10px">
      {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">Ingredients</div>
        <div class="panel-body">
          {{ recipe.ingredients_html | safe }}
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">Recipe Steps</div>
        <div class="panel-body">
          {{ recipe.recipe_steps_html | safe }}
        </div>
      </div>
    </div>
  </div>

</div>`

{% endblock %}

web/project/templates/register.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
  <div class="page-header">
    <h2>Please Register Your New Account</h2>
  </div>
  <form action="{{ url_for('users.register') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
      {{ render_field(form.confirm, placeholder="Confirm password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Create New Account</button>
  </form>
</div>

{% endblock %}

web/project/templates/reset_password_with_token.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">
  <div class="page-header">
    <h2>New Password:</h2>
  </div>
  <form action="{{ url_for('users.reset_with_token', token=token) }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Enter New Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

web/project/templates/user_recipes.html
{% extends "layout.html" %}
{% block content %}

<div class="user-recipes">
  <div class="page-header">
    <h2>My Recipes - {{ recipe_type }}</h2>
  </div>

  <div class="container">
    {% if user_recipes.count() == 0 %}
      <h5>No recipes have been created!</h5>
    {% else %}
      <ul class="media-list">
        {% for recipe in user_recipes %}
          <li class="media">
            <div class="media-left">
              <a class="media-left" href="{{ url_for('recipes.recipe_details', recipe_id=recipe.id) }}">
                <img class="media-object" src="{{ recipe.image_url }}" alt="{{ recipe.image_filename }}" style="width:64;height:64px;">
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">
                <a href="{{ url_for('recipes.recipe_details', recipe_id=recipe.id) }}">{{ recipe.recipe_title }}</a>
                {% if recipe.dairy_free_recipe %}
                  <span class="label label-info" style="font-size:10px;">Dairy-Free</span>
                {% endif %}
                {% if recipe.soy_free_recipe %}
                  <span class="label label-success" style="font-size:10px;">Soy-Free</span>
                {% endif %}
              </h4>
              {{ recipe.recipe_description }}
            </div>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>

{% endblock %}

web/project/templates/whats_for_dinner.html
{% extends "layout.html" %}
{% block content %}

<div class="user-profile">
  {% if not recipe_found %}
    <div class="page-header">
      <h2>What's for Dinner?</h2>
      <h2>Sorry, no dinner recipes were found!</h2>
    </div>
  {% elif takeout_recommendation %}
    <div class="page-header">
      <h2>What's for Dinner?</h2>
      <h2>Dinner Recommendation: Takeout from your favorite restaurant!</h2>
    </div>
  {% else %}
    <div class="page-header">
      <h2>What's for Dinner?... {{ recipe.recipe_title }}</h2>
    </div>

    <div class="row">
      <div class="col-xs-6 col-md-4">
        <div class="panel panel-primary">
          <div class="panel-heading">Description</div>
          <div class="panel-body">{{ recipe.recipe_description }}</div>
        </div>

        <div class="panel panel-primary">
          <div class="panel-heading">Public or Private</div>
          {% if recipe.is_public %}
            <div class="panel-body">Public</div>
          {% else %}
            <div class="panel-body">Private</div>
          {% endif %}
        </div>

        <div class="panel panel-primary">
          <div class="panel-heading">Recipe Type</div>
          <div class="panel-body">{{ recipe.recipe_type }}</div>
        </div>

        <div class="panel panel-primary">
          <div class="panel-heading">Rating (1-worst to 5-best)</div>
          <div class="panel-body">{{ recipe.rating }}</div>
        </div>
      </div>

      <div class=".col-xs-6 .col-md-8">
        {% if recipe.image_url %}
          <img src="{{ recipe.image_url }}" alt="{{ recipe.image_filename }}" style="width:600px;height:450px;">
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">Ingredients</div>
          <div class="panel-body">
            {{ recipe.ingredients_html | safe }}
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">Recipe Steps</div>
          <div class="panel-body">
            {{ recipe.recipe_steps_html | safe }}
          </div>
        </div>
      </div>
    </div>
  {% endif %}

</div>`

{% endblock %}